"""initial

Revision ID: 04c02d00b33d
Revises: d7c25e92d36a
Create Date: 2024-05-05 01:57:12.565144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04c02d00b33d'
down_revision: Union[str, None] = 'd7c25e92d36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(50)),
        sa.Column('username', sa.String(100), nullable=False, unique=True),
        sa.Column('password', sa.String(100), nullable=False),
    )

    # Create sale_receipts table
    op.create_table('sale_receipts',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('products', sa.JSON(), nullable=False),
        sa.Column('payment_type', sa.String(50), nullable=False),
        sa.Column('payment_amount', sa.Float(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('rest_amount', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), default=sa.func.now()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(length=450), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=450), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('access_token', name='token_pkey')
    )
    # ### end Alembic commands ###
