"""initial

Revision ID: 10cdf3518d03
Revises: b3328f34934d
Create Date: 2024-05-02 17:35:49.349504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10cdf3518d03'
down_revision: Union[str, None] = 'b3328f34934d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_toke', sa.VARCHAR(length=450), autoincrement=False, nullable=False),
    sa.Column('refresh_toke', sa.VARCHAR(length=450), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('access_toke', name='token_pkey')
    )
    # ### end Alembic commands ###
