"""initial

Revision ID: 70c4838237c4
Revises: 5ae7291b0b31
Create Date: 2024-05-03 10:07:45.323447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c4838237c4'
down_revision: Union[str, None] = '5ae7291b0b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String(50), nullable=False),
        sa.Column('email', sa.String(100), unique=True, nullable=False),
        sa.Column('password', sa.String(100), nullable=False)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.add_column('token', sa.Column('refresh_token', sa.VARCHAR(length=450), autoincrement=False, nullable=False))
    op.add_column('token', sa.Column('access_token', sa.VARCHAR(length=450), autoincrement=False, nullable=False))
    op.alter_column('token', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('token', 'refresh_toke')
    op.drop_column('token', 'access_toke')
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    # ### end Alembic commands ###
