"""initial

Revision ID: cd18104e9061
Revises: 70c4838237c4
Create Date: 2024-05-03 13:04:36.196800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision: str = 'cd18104e9061'
down_revision: Union[str, None] = '70c4838237c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'token',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer),
        sa.Column('access_token', sa.String(450), primary_key=True),
        sa.Column('refresh_token', sa.String(450), nullable=False),
        sa.Column('status', sa.Boolean),
        sa.Column('created_date', sa.DateTime, default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.drop_table('token')
    # ### end Alembic commands ###
